import esbuild from 'esbuild';
import builtins from "builtin-modules";
import fs from 'fs';

const jsdomPatch = {
    name: 'jsdom-patch',
    setup(build) {
        build.onLoad({ filter: /\.js$/, namespace: 'file' }, (args) => {
            if (args.path.includes('jsdom/lib/jsdom/living/xhr/xhr-sync-worker.js')) {
                return {
                    contents: '// Empty file or replacement implementation',
                    loader: 'js'
                };
            }
        });
    },
};

esbuild.build({
    banner: {
        js: '/* This is an autogenerated file. Do not edit this file directly. */\n'
    },
    entryPoints: ['src/index.ts'],
    bundle: true,
    outfile: 'dist/index.js',
    target: 'es2020',
    external: [
        ...builtins
    ],
    format: 'cjs',
    // watch: process.argv.includes('--watch'),
    logLevel: 'info',
    sourcemap: process.argv.includes('--sourcemap'),
    treeShaking: true,
    platform: 'node',
    plugins: [jsdomPatch],
}).catch(() => process.exit(1));
