import esbuild from 'esbuild';
import builtins from "builtin-modules";
import fs from 'fs';

const jsdomPatch = {
    name: 'jsdom-patch',
    setup(build) {
        build.onLoad({ filter: /\.js$/, namespace: 'file' }, (args) => {
            if (args.path.includes('jsdom/lib/jsdom/living/xhr/xhr-sync-worker.js')) {
                return {
                    contents: '// Empty file or replacement implementation',
                    loader: 'js'
                };
            }
        });
    },
};

const buildOptions = {
    banner: {
        js: '/* This is an autogenerated file. Do not edit this file directly. */\n'
    },
    bundle: true,
    target: 'es2020',
    external: [
        ...builtins,
        're2',
        'canvas',
        'bufferutil',
        'utf-8-validate'
    ],
    format: 'cjs',
    logLevel: 'info',
    sourcemap: process.argv.includes('--sourcemap'),
    treeShaking: true,
    platform: 'node',
    plugins: [jsdomPatch],
};

// Build library
await esbuild.build({
    ...buildOptions,
    entryPoints: ['src/index.ts'],
    outfile: 'dist/index.js',
}).catch(() => process.exit(1));

// Build CLI
await esbuild.build({
    ...buildOptions,
    entryPoints: ['src/cli.ts'],
    outfile: 'dist/cli.js',
    banner: {
        js: '#!/usr/bin/env node\n/* This is an autogenerated file. Do not edit this file directly. */\n'
    },
}).catch(() => process.exit(1));
